#' Roclet: global
#'
#' @importFrom roxygen2 roclet
#' @export
global_roclet <- function() roxygen2::roclet("global")

#' @importFrom roxygen2 roclet_process
#' @export
roclet_process.roclet_global <- function(x, blocks, env, base_path) {
  blocks_to_globals(blocks)
}

#' @importFrom roxygen2 roclet_output
#' @export
roclet_output.roclet_global <- function(x, results, base_path, ...) {
  stringi::stri_write_lines(results, globals_path(base_path))
  invisible(NULL)
}

#' @importFrom roxygen2 roclet_clean
#' @export
roclet_clean.roclet_global <- function(x, base_path) {
  unlink(globals_path(base_path), force = TRUE)
}

#' @importFrom roxygen2 roxy_tag_parse
#' @export
roxy_tag_parse.roxy_tag_global <- function(x) {
  if (x$raw == "") return(roxygen2::roxy_tag_warning(x, "requires a value"))

  roxygen2::tag_words(x, min = 1)
}

#' @importFrom roxygen2 roxy_tag_parse
#' @export
roxy_tag_parse.roxy_tag_autoglobal <- function(x) roxygen2::tag_toggle(x)


blocks_to_globals <- function(blocks) {
  globals <- lapply(blocks, block_to_globals) %>%
    unlist() %>%
    c("  NULL") %>%
    paste0(collapse = "\n")

  paste(
    sep = "\n",
    generated_by(),
    "utils::globalVariables(c(",
      globals,
    "))"
  )
}

block_to_globals <- function(block) {
  explicit_globals <- roxygen2::block_get_tags(block, "global") %>%
    lapply(function(tag) tag$val) %>%
    unlist()

  fn <- block$object$value
  auto_globals <- if (roxygen2::block_has_tags(block, "autoglobal") && is.function(fn))
    extract_globals(fn)

  globals <- unique(c(explicit_globals, auto_globals))
  if (length(globals)) {
    fn_name <- block$object$alias
    paste0("  ", lapply(globals, dQuote, FALSE), ", # <", fn_name, ">")
  }
}

generated_by <- function() {
  paste0("# Generated by ", utils::packageName(), ": do not edit by hand\n")
}

globals_path <- function(base_path) file.path(base_path, "R", "globals.R")
