
#' Roclet: global
#'
#' @importFrom roxygen2 roclet
#' @export
global_roclet <- function() roxygen2::roclet("global")

#' @importFrom roxygen2 roclet_process
#' @export
roclet_process.roclet_global <- function(x, blocks, env, base_path) {
  lapply(blocks, function(block) roxygen2::block_get_tags(block, "global")) %>%
    unlist(recursive = FALSE) %>%
    lapply(function(tag) tag$val) %>%
    unlist() %>%
    sort() %>%
    unique()
}

#' @importFrom roxygen2 roclet_output
#' @export
roclet_output.roclet_global <- function(x, results, base_path, ...) {
  vars <- paste0("  ", dQuote(results, FALSE), collapse = ",\n")
  contents <- paste(
    sep = "\n",
    paste0("# Generated by ", utils::packageName(), ": do not edit by hand\n"),
    "utils::globalVariables(c(",
      vars,
    "))"
  )

  stringi::stri_write_lines(contents, globals_path(base_path))
  invisible(NULL)
}

#' @importFrom roxygen2 roclet_clean
#' @export
roclet_clean.roclet_global <- function(x, base_path) {
  unlink(globals_path(base_path), force = TRUE)
}

#' @importFrom roxygen2 roxy_tag_parse
#' @export
roxy_tag_parse.roxy_tag_global <- function(x) roxygen2::tag_words_line(x)

globals_path <- function(base_path) file.path(base_path, "R", "globals.R")
